apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  labels:
    app: gitops-demo
spec:
  type: LoadBalancer
  selector:
    app: gitops-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
